# Generated by Django 4.0.6 on 2022-07-16 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=150, verbose_name='Chapter title')),
                ('body', models.TextField(default='', verbose_name='Chapter text')),
                ('word_count', models.IntegerField(default=0, verbose_name='Word count')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Created time')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='last update')),
                ('publish_status', models.CharField(choices=[('Published', 'Published'), ('Draft', 'Draft'), ('Trash', 'Trash')], default='Published', max_length=150)),
                ('is_vip', models.BooleanField(default=False, verbose_name='VIP chapter')),
                ('coin_price', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'chapter',
                'verbose_name_plural': 'chapters',
                'db_table': 'Chapter',
            },
        ),
    ]
